/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GhostPaymasterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateFee"
      | "claimGasReimbursement"
      | "depositFee"
      | "feeBasisPoints"
      | "feeDeposits"
      | "owner"
      | "relayer"
      | "renounceOwnership"
      | "setFeeBasisPoints"
      | "setRelayer"
      | "transferOwnership"
      | "withdrawFeeTokens"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeBasisPointsUpdated"
      | "FeeDeposited"
      | "GasReimbursed"
      | "OwnershipTransferred"
      | "RelayerUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimGasReimbursement",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFee",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeBasisPoints",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeDeposits",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "relayer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeBasisPoints",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFeeTokens",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimGasReimbursement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeBasisPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeBasisPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRelayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFeeTokens",
    data: BytesLike
  ): Result;
}

export namespace FeeBasisPointsUpdatedEvent {
  export type InputTuple = [oldBps: BigNumberish, newBps: BigNumberish];
  export type OutputTuple = [oldBps: bigint, newBps: bigint];
  export interface OutputObject {
    oldBps: bigint;
    newBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeDepositedEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, token: string, amount: bigint];
  export interface OutputObject {
    user: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GasReimbursedEvent {
  export type InputTuple = [relayer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [relayer: string, amount: bigint];
  export interface OutputObject {
    relayer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerUpdatedEvent {
  export type InputTuple = [oldRelayer: AddressLike, newRelayer: AddressLike];
  export type OutputTuple = [oldRelayer: string, newRelayer: string];
  export interface OutputObject {
    oldRelayer: string;
    newRelayer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GhostPaymaster extends BaseContract {
  connect(runner?: ContractRunner | null): GhostPaymaster;
  waitForDeployment(): Promise<this>;

  interface: GhostPaymasterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateFee: TypedContractMethod<[amount: BigNumberish], [bigint], "view">;

  claimGasReimbursement: TypedContractMethod<
    [gasUsed: BigNumberish, gasPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositFee: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeBasisPoints: TypedContractMethod<[], [bigint], "view">;

  feeDeposits: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  relayer: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFeeBasisPoints: TypedContractMethod<
    [_feeBasisPoints: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRelayer: TypedContractMethod<
    [_relayer: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawFeeTokens: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateFee"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimGasReimbursement"
  ): TypedContractMethod<
    [gasUsed: BigNumberish, gasPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositFee"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeBasisPoints"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeDeposits"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "relayer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeBasisPoints"
  ): TypedContractMethod<[_feeBasisPoints: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRelayer"
  ): TypedContractMethod<[_relayer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFeeTokens"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FeeBasisPointsUpdated"
  ): TypedContractEvent<
    FeeBasisPointsUpdatedEvent.InputTuple,
    FeeBasisPointsUpdatedEvent.OutputTuple,
    FeeBasisPointsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeDeposited"
  ): TypedContractEvent<
    FeeDepositedEvent.InputTuple,
    FeeDepositedEvent.OutputTuple,
    FeeDepositedEvent.OutputObject
  >;
  getEvent(
    key: "GasReimbursed"
  ): TypedContractEvent<
    GasReimbursedEvent.InputTuple,
    GasReimbursedEvent.OutputTuple,
    GasReimbursedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RelayerUpdated"
  ): TypedContractEvent<
    RelayerUpdatedEvent.InputTuple,
    RelayerUpdatedEvent.OutputTuple,
    RelayerUpdatedEvent.OutputObject
  >;

  filters: {
    "FeeBasisPointsUpdated(uint256,uint256)": TypedContractEvent<
      FeeBasisPointsUpdatedEvent.InputTuple,
      FeeBasisPointsUpdatedEvent.OutputTuple,
      FeeBasisPointsUpdatedEvent.OutputObject
    >;
    FeeBasisPointsUpdated: TypedContractEvent<
      FeeBasisPointsUpdatedEvent.InputTuple,
      FeeBasisPointsUpdatedEvent.OutputTuple,
      FeeBasisPointsUpdatedEvent.OutputObject
    >;

    "FeeDeposited(address,address,uint256)": TypedContractEvent<
      FeeDepositedEvent.InputTuple,
      FeeDepositedEvent.OutputTuple,
      FeeDepositedEvent.OutputObject
    >;
    FeeDeposited: TypedContractEvent<
      FeeDepositedEvent.InputTuple,
      FeeDepositedEvent.OutputTuple,
      FeeDepositedEvent.OutputObject
    >;

    "GasReimbursed(address,uint256)": TypedContractEvent<
      GasReimbursedEvent.InputTuple,
      GasReimbursedEvent.OutputTuple,
      GasReimbursedEvent.OutputObject
    >;
    GasReimbursed: TypedContractEvent<
      GasReimbursedEvent.InputTuple,
      GasReimbursedEvent.OutputTuple,
      GasReimbursedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RelayerUpdated(address,address)": TypedContractEvent<
      RelayerUpdatedEvent.InputTuple,
      RelayerUpdatedEvent.OutputTuple,
      RelayerUpdatedEvent.OutputObject
    >;
    RelayerUpdated: TypedContractEvent<
      RelayerUpdatedEvent.InputTuple,
      RelayerUpdatedEvent.OutputTuple,
      RelayerUpdatedEvent.OutputObject
    >;
  };
}
